# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-17 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20171117_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortiturl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
