# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-27 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20171117_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortiturl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
